/*
COPYRIGHT (c)2021 Christian Brunner

Executes an system command. Using qcmdexc

Incoming Parameter:
 - System command to execute
 
Returns 0 by success and -1 due failure
*/


CREATE OR REPLACE FUNCTION BRUNNER.EXECUTECOMMAND
( 
	PARM_COMMAND VARCHAR(32000)
)

RETURNS SMALLINT

LANGUAGE SQL
SPECIFIC BRUNNER.EXCCMD
DETERMINISTIC
MODIFIES SQL DATA
CALLED ON NULL INPUT

SET OPTION
 COMMIT = *NONE,
 DBGVIEW = *SOURCE,
 DYNUSRPRF = *OWNER

BEGIN
 DECLARE CONTINUE HANDLER FOR SQLEXCEPTION RETURN -1;

 CALL QCMDEXC(PARM_COMMAND);

 RETURN 0;

END;

COMMENT ON PARAMETER SPECIFIC FUNCTION BRUNNER.EXCCMD
( 
    PARM_COMMAND IS 'Command to execute'
);

LABEL ON SPECIFIC FUNCTION BRUNNER.EXCCMD IS 'Execute system command';         