CREATE OR REPLACE TABLE library.import_h
(

 h_id BIGINT GENERATED ALWAYS AS IDENTITY
		(START WITH 0 INCREMENT BY 1 NO MINVALUE NO MAXVALUE NO CYCLE NO ORDER NO CACHE), 
 h_cus CHAR(10) NOT NULL , 
 h_sts SMALLINT DEFAULT NULL , 
 h_dau TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , 
 h_ghp TIMESTAMP DEFAULT NULL , 
 h_ghp VARCHAR(128) ALLOCATE(10) DEFAULT USER
 
) RCDFMT import00; 
  
CREATE OR REPLACE TRIGGER library.import 
	AFTER UPDATE OF h_sts ON library.import_h 
	REFERENCING OLD AS old_import NEW AS new_import FOR EACH ROW MODE DB2SQL
	WHEN ( OLD_IMPORT . H_STS IS NULL AND NEW_IMPORT . H_STS = 1 )
 BEGIN ATOMIC 
   CALL QSYS2.SEND_DATA_QUEUE
	(MESSAGE_DATA => DIGITS(old_import.h_id), 
	 DATA_QUEUE => 'IMPORT_H', 
	 DATA_QUEUE_LIBRARY => 'LIBRARY');
 END;
 