CREATE OR REPLACE FUNCTION LIB.DATE2DEC (IN_DATE DATE)
 RETURNS DECIMAL (8, 0)
 LANGUAGE SQL
 DETERMINISTIC
 READS SQL DATA
 CALLED ON NULL INPUT
 NO EXTERNAL ACTION
 NOT SECURED

BEGIN

 DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
  BEGIN
   RETURN NULL;
  END;

 RETURN DEC(IN_DATE, 8, 0);

END;