CREATE OR REPLACE FUNCTION YOUR_SCHEMA.TIMESTAMP_UNIX ( 
 PARM_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
 PARM_TIMEZONE DECIMAL(6, 0) DEFAULT CURRENT_TIMEZONE ) 
  RETURNS BIGINT   
  LANGUAGE SQL 
  SPECIFIC YOUR_SCHEMA.TS_UNIX 
  DETERMINISTIC 
  MODIFIES SQL DATA 
  CALLED ON NULL INPUT 
  SET OPTION COMMIT = *NONE, DBGVIEW = *SOURCE, DYNUSRPRF = *OWNER

BEGIN 
 DECLARE CONTINUE HANDLER FOR SQLEXCEPTION RETURN -1; 
  
 RETURN 
  (BIGINT(DAYS(PARM_TIMESTAMP - PARM_TIMEZONE) - DAYS('1970-01-01')) * 86400) + MIDNIGHT_SECONDS(PARM_TIMESTAMP - PARM_TIMEZONE);

END; 

LABEL ON SPECIFIC FUNCTION YOUR_SCHEMA.TS_UNIX 
	IS 'Timestamp in unix-format'; 

COMMENT ON PARAMETER SPECIFIC FUNCTION YOUR_SCHEMA.TS_UNIX 
(PARM_TIMEZONE IS 'Timezone (-)HHMMSS'); 