/*
COPYRIGHT (c)2021 Christian Brunner

Convert timestamp to iso 8601 timestamp

Incoming Parameter:
 - Timestamp
 
Returns iso 8601 timestamp or -1 on failure
*/

CREATE FUNCTION BRUNNER.TIMESTAMP_ISO8601 
( 
 PARM_TIMESTAMP TIMESTAMP DEFAULT  CURRENT_TIMESTAMP,
 PARM_TIMEZONE DECIMAL(6, 0) DEFAULT  CURRENT_TIMEZONE
)
 
 RETURNS VARCHAR(26)   
 LANGUAGE SQL 
 SPECIFIC BRUNNER/TS_ISO8601 
 DETERMINISTIC 
 MODIFIES SQL DATA 
 CALLED ON NULL INPUT 
  
BEGIN 
  
 DECLARE CONTINUE HANDLER FOR SQLEXCEPTION RETURN '-1'; 
  
 RETURN 
 ( 
   TRANSLATE ( VARCHAR_FORMAT ( PARM_TIMESTAMP , 'YYYY-MM-DD HH24:MI:SS' ) , 'T' , ' ' ) CONCAT 
     CASE WHEN PARM_TIMEZONE < 0 THEN '-' ELSE '+' END CONCAT VARCHAR_FORMAT ( '00010101' CONCAT RIGHT ( DIGITS ( PARM_TIMEZONE ) , 6 ) , 'HH24:MI' ) 
  ); 
  
END; 
  
COMMENT ON PARAMETER SPECIFIC FUNCTION BRUNNER.TS_ISO8601 ( PARM_TIMEZONE IS 'Timezone (-)HHMMSS' ); 
  
LABEL ON SPECIFIC FUNCTION BRUNNER.TS_ISO8601 IS 'Timestamp to ISO8601 (YYYY-MM-DDTHH:MM:SS+/-HH:MM)'; 